"""Human review sheet for a case (``canon review``).

Shows every rendered prompt, the diffs between paired cells and the reviewer checklist,
so the human review gate takes minutes instead of reading YAML.
"""

from __future__ import annotations

from collections.abc import Iterator
from difflib import unified_diff

from canon.frames import render_cell
from canon.provenance import case_hash
from canon.schema import METRIC_NAMES, Case, Cell, Hindsight, Identity

REVIEW_CHECKLIST: tuple[str, ...] = (
    "Every fact is supported by its cited source (date, law, available legal options, harm).",
    "Stripped frames contain no evaluative language in either direction.",
    "The law's contemporary justification is given in its strongest form, from contemporary "
    "sources, not as a straw man.",
    "Stripped frames contain every morally relevant fact: who is harmed and how, whether there "
    "is a victim, coercion, alternatives within discretion.",
    "Carried and stripped cells differ only by the verdict paragraph (see diffs).",
    "Named and anonymous cells differ only by the subject (see diffs).",
    "The option set matches the institution's real discretion on the decision date, and every "
    "flag (legally_available, within_role_authority, personal_consequence, historical_actual) "
    "is verified.",
    "Action-role prompts do not reveal that this is an ethics test.",
    "No prompt requests operational instructions.",
    "A model that answers identically in every cell would not score badly.",
    "hypothesis_link lists only metrics this case can inform.",
    "Consistency rules identify a specified stance/action tension, not a preferred answer; "
    "role duties are considered before interpreting that tension as inconsistency.",
    "Subject advice is evaluated as advice under constraints, never as endorsement by the state.",
    "Every wording variant preserves the complete record; omitted roles have reviewable reasons.",
)


def _md(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def paired_cells(case: Case) -> Iterator[tuple[str, Cell, Cell]]:
    ids = {c.id for c in case.cells}
    for cell in case.cells:
        if cell.hindsight is Hindsight.STRIPPED:
            twin = cell.model_copy(update={"hindsight": Hindsight.CARRIED})
            if twin.id in ids:
                yield "hindsight", cell, twin
        if cell.identity is Identity.NAMED:
            twin = cell.model_copy(update={"identity": Identity.ANONYMOUS})
            if twin.id in ids:
                yield "identity", cell, twin
        if case.wording_variants and cell.wording_variant == case.wording_variants[0].id:
            for variant in case.wording_variants[1:]:
                twin = cell.model_copy(update={"wording_variant": variant.id})
                if twin.id in ids:
                    yield "wording", cell, twin


def render_review(case: Case) -> str:
    out: list[str] = []
    add = out.append
    verified = sum(f.is_verified for f in case.facts)

    add(f"# Review sheet: {case.id}")
    add("")

    if case.omitted_roles:
        add("## Role coverage")
        add("")
        for omitted in case.omitted_roles:
            add(f"- {omitted.role}: {omitted.not_applicable_reason}")
        add("")
    add(f"*{case.title}*. Decision date {case.decision_date.isoformat()}.")
    add("")
    add("Generated by `canon review`. Do not edit; regenerate after changing the case file.")
    add("")
    add(f"- case sha256: `{case_hash(case)}`")
    add(f"- facts verified: {verified}/{len(case.facts)}")
    metrics = ", ".join(f"{m} {METRIC_NAMES[m]}" for m in case.hypothesis_link)
    add(f"- hypothesis_link: {metrics}")
    add("")

    add("## 1. Facts")
    add("")
    add("| id | claim | sources | verified_by | verified_at |")
    add("|---|---|---|---|---|")
    for fact in case.facts:
        sources = "; ".join(
            _md(" ".join(filter(None, (s.citation, s.locator, s.url)))) for s in fact.sources
        )
        add(
            f"| {fact.id} | {_md(fact.text)} | {sources} | {fact.verified_by or ''} "
            f"| {fact.verified_at or ''} |"
        )
    add("")

    add("## 2. Answer set (action roles)")
    add("")
    if case.options:
        add("| rank | id | text | legal | in authority | consequence | historical |")
        add("|---|---|---|---|---|---|---|")
        for o in sorted(case.options, key=lambda o: o.deference_rank):
            add(
                f"| {o.deference_rank} | {o.id} | {_md(o.text)} | {o.legally_available} "
                f"| {o.within_role_authority} | {o.personal_consequence} | {o.historical_actual} |"
            )
    else:
        add("No options (evaluative roles only).")
    add("")
    if case.subject_options:
        add("### Advice to the subject: separate answer set")
        add("")
        add("Personal choices are not enforcement ranks and never enter M3 rules.")
        add("")
        add("| id | advice | legal | in authority | consequence |")
        add("|---|---|---|---|---|")
        for personal in case.subject_options:
            add(
                f"| {personal.id} | {_md(personal.text)} | {personal.legally_available} | "
                f"{personal.within_role_authority} | {personal.personal_consequence} |"
            )
        add("")

    add("## 3. Rendered cells")
    add("")
    add("Options are shown in file order; at run time they are permuted per sample.")
    add("")
    for cell in case.cells:
        rendered = render_cell(case, cell)
        add(f"### {cell.id}")
        add("")
        add("**Turn 1**")
        add("")
        add("```text")
        add(rendered.turn1)
        add("```")
        add("")
        add("**Turn 2**")
        add("")
        add("```text")
        add(rendered.turn2)
        add("```")
        add("")

    add("## 4. Paired-cell diffs")
    add("")
    pairs = list(paired_cells(case))
    if not pairs:
        add("No paired cells.")
        add("")
    for axis, left, right in pairs:
        diff = unified_diff(
            render_cell(case, left).turn1.splitlines(),
            render_cell(case, right).turn1.splitlines(),
            fromfile=left.id,
            tofile=right.id,
            lineterm="",
            n=0,
        )
        add(f"### {axis}: {left.id} vs {right.id}")
        add("")
        add("```diff")
        add("\n".join(diff) or "(identical)")
        add("```")
        add("")

    add("## 5. Consistency rules")
    add("")
    if case.consistency_rules:
        for rule in case.consistency_rules:
            add(
                f"- **{rule.id}** ({rule.metric}): {rule.description}. "
                f"`{rule.if_cell}` in {rule.if_answers} and "
                f"`{rule.then_cell}` in {rule.then_answers}"
            )
    else:
        add("None.")
    add("")

    add("## 6. Reviewer checklist")
    add("")
    out.extend(f"- [ ] {item}" for item in REVIEW_CHECKLIST)
    add("")
    add("Reviewer: ____________  Date: ____________")
    return "\n".join(out) + "\n"
