"""Generate the historical bibliography of the case bank.

    uv run python scripts/make_sources_bib.py

Every fact in every active case cites a source. This collects them, de-duplicates by URL and
writes:

- `paper/sources.tex`   an appendix table: case, fact, citation with its URL, locator, and
                        whether the fact is signed by the verification pass

No BibTeX file: 47 `@misc` entries whose only content is a title and a URL add nothing that the
table does not already show, and long URLs inside generated entries break the bibliography.

The paper's historical claims are therefore cited from the same strings the models were shown,
not from a separately maintained list.
"""

from __future__ import annotations

import re
from pathlib import Path

from canon.validate import load_cases

ROOT = Path(__file__).resolve().parent.parent


def escape(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    out = text.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")
    return out.replace("$", r"\$")


def main() -> None:
    cases = sorted(load_cases([ROOT / "cases"]), key=lambda c: str(c.decision_date))
    by_url: dict[str, tuple[str, str]] = {}  # url -> (key, citation)
    rows: list[tuple[str, str, str, str, str]] = []
    for case in cases:
        for fact in case.facts:
            for source in fact.sources:
                url = str(source.url)
                if url not in by_url:
                    by_url[url] = (f"src:{len(by_url) + 1}", source.citation)
                key, _ = by_url[url]
                rows.append(
                    (
                        case.id,
                        fact.id,
                        key,
                        source.locator or "",
                        "yes" if fact.verified_by else "NO",
                    )
                )
    tex = [
        "% Generated by scripts/make_sources_bib.py. Do not edit by hand.",
        "\\section{Sources of the case records}",
        "",
        "Every fact in a case record cites a source; the questions, the instructions and some",
        "answer options were written by the author, and several options lack adequate source",
        "support. A fact counts as",
        "\\emph{signed} when both verifying models could ground it in the cited source and the",
        "author reviewed the report; unsigned facts are listed as such. They",
        "remain in the prompts, and findings on the affected cases inherit that limitation.",
        "",
        "\\small",
        "\\begin{longtable}{>{\\RaggedRight}p{2.6cm}>{\\RaggedRight}p{2.2cm}"
        ">{\\RaggedRight}p{7.5cm}p{1.0cm}}",
        "\\toprule",
        "Case & Fact & Source & Signed \\\\",
        "\\midrule",
        "\\endhead",
    ]
    seen: set[tuple[str, str, str]] = set()
    for case_id, fact_id, key, locator, signed in rows:
        if (case_id, fact_id, key) in seen:
            continue
        seen.add((case_id, fact_id, key))
        citation = escape(by_url_citation(by_url, key))
        url = next(u for u, (candidate, _) in by_url.items() if candidate == key)
        loc = f" ({escape(locator)})" if locator else ""
        tex.append(
            f"{escape(case_id)} & {escape(fact_id)} & {citation}{loc}. "
            f"\\url{{{url}}} & {signed} \\\\"
        )
    tex += ["\\bottomrule", "\\end{longtable}", ""]
    (ROOT / "paper" / "sources.tex").write_text("\n".join(tex), encoding="utf-8", newline="\n")
    print(
        f"wrote paper/sources.tex: {len(seen)} fact-source rows over {len(by_url)} distinct sources"
    )


def by_url_citation(by_url: dict[str, tuple[str, str]], key: str) -> str:
    for _, (candidate, citation) in by_url.items():
        if candidate == key:
            return re.sub(r"\s+", " ", citation).strip()
    return key


if __name__ == "__main__":
    main()
