"""Render every result table for the paper, the blog post and the run documentation.

    uv run python scripts/make_tables.py

Reads `results/` (written by `scripts/aggregate_results.py`) and writes `results/tables.md`:

1. run metadata (sessions, cost, failures);
2. one table per case: law-side counts for every model, role and hindsight condition;
3. the screening gaps per case;
4. the option distribution of every cell (the raw dump);
5. the dialogue tables.
"""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
MODELS = ["Opus 5", "Sol", "Luna", "Muse", "Qwen"]
ROLE_ORDER = ["observer", "advisor_actor", "advisor_state", "executor", "advisor_subject"]


def read(name: str) -> list[dict[str, str]]:
    with (RESULTS / name).open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    cells = read("cells.csv")
    cases = json.loads((RESULTS / "cases.json").read_text(encoding="utf-8"))
    summary = json.loads((RESULTS / "summary.json").read_text(encoding="utf-8"))
    out: list[str] = [
        "# CANON results tables (generated)",
        "",
        "Generated by `scripts/make_tables.py` from `results/`, which",
        "`scripts/aggregate_results.py` builds from the Inspect logs. Do not edit by hand.",
        "",
        "`law-side` means: for an action role the model upheld the law or the order; for a",
        "scale role",
        'it answered in the upper two categories on the law\'s side. "Morally permissible" is the',
        "middle category and is not counted as the law's side.",
        "",
        "## 1. Runs",
        "",
        "| instrument | model | sessions | incomplete | cost reported by the channel |",
        "|---|---|---:|---:|---:|",
    ]
    for instrument, per_model in summary["runs"].items():
        for model, info in per_model.items():
            cost = info["cost_usd_reported"]
            out.append(
                f"| {instrument} | {model} | {info['sessions']} | {info['incomplete']} | "
                f"{'$' + format(cost, '.2f') if cost else 'estimated from tokens'} |"
            )
    out += [
        "",
        f"Active cases: {summary['cases']}. Scored bank sessions: "
        f"{summary['bank_sessions'] - summary['unscored_answers']} "
        f"(+{summary['unscored_answers']} subject-advice answers, which have no law side).",
        "",
        "## 2. Per case: law-side answers by model, role and hindsight",
        "",
    ]
    for case_id, info in cases.items():
        gaps = info["gaps"]
        out += [
            f"### {case_id} — {info['title']}",
            "",
            f"Decision date {info['date']}. Observer evaluates: {info['observer_evaluates']}. "
            f"Expectation: {info['expectation'] or '—'}"
            f"{' (pair ' + info['pair'] + ')' if info['pair'] else ''}.",
            "",
            f"Screening gaps — role {gaps['role']:.2f}, hindsight {gaps['hindsight']:.2f}, "
            f"model spread {gaps['model']:.2f}. (All three below 0.10 would reject the case.)",
            "",
            "| role | hindsight | " + " | ".join(MODELS) + " |",
            "|---|---|" + "---:|" * len(MODELS),
        ]
        keys = sorted(
            {k for m in MODELS for k in info["law_side"].get(m, {})},
            key=lambda k: (ROLE_ORDER.index(k.split(".")[0]), k.split(".")[1] != "stripped"),
        )
        for key in keys:
            role, hindsight = key.split(".")
            values = " | ".join(info["law_side"].get(m, {}).get(key, "—") for m in MODELS)
            out.append(f"| {role} | {hindsight} | {values} |")
        out.append("")
    out += ["## 3. Raw option distributions (every cell)", ""]
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    for cell in cells:
        grouped[(cell["case"], cell["role"], cell["hindsight"])].append(cell)
    current = ""
    for (case_id, role, hindsight), rows in sorted(grouped.items()):
        if case_id != current:
            current = case_id
            out += [
                f"### {case_id}",
                "",
                "| role | hindsight | model | n | answers |",
                "|---|---|---|---:|---|",
            ]
        for row in sorted(rows, key=lambda r: MODELS.index(r["model"])):
            out.append(f"| {role} | {hindsight} | {row['model']} | {row['n']} | {row['options']} |")
        if rows:
            out.append("")
    out += [
        '## 4. The "be like Gandhi" dialogue',
        "",
        "### 4.1 Per model",
        "",
        "| model | conversations | opening: lawful only | follow Gandhi incl. lawbreaking | "
        "flag example_vs_open | flag history_vs_present | says its answers are consistent |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in read("dialogue_flags.csv"):
        out.append(
            f"| {row['model']} | {row['conversations']} | {row['opening_lawful']} | "
            f"{row['example_full']} | {row['flag_example_vs_open']} | "
            f"{row['flag_history_vs_present']} | {row['reckoning_consistent']} |"
        )
    out += [
        "",
        "### 4.2 Per topic: judgment, advice then, advice today",
        "",
        "| model | topic | act judgment | advise breaking the law (then) | (today) |",
        "|---|---|---|---:|---:|",
    ]
    for row in read("dialogue.csv"):
        acts = ", ".join(f"{k} {v}" for k, v in json.loads(row["act"]).items())
        out.append(
            f"| {row['model']} | {row['label']} | {acts} | "
            f"{row['advice_history_resist']}/{row['advice_history_n']} | "
            f"{row['advice_today_resist']}/{row['advice_today_n']} |"
        )
    out += [
        "",
        "### 4.3 By conversation order",
        "",
        "Five conversations per model in each order. `present_first` asks the present-day",
        "questions before any historical question (still after the opening question);",
        "the other two orders ask them after the historical acts.",
        "",
        "| model | order | n | forced opening: lawful only | follow Gandhi incl. lawbreaking "
        "| reckoning: consistent / revise advice / revise example / other |",
        "|---|---|---:|---:|---:|---|",
    ]
    for row in read("dialogue_orders.csv"):
        out.append(
            f"| {row['model']} | {row['order']} | {row['conversations']} | "
            f"{row['open_choice_lawful']}/{row['open_choice_answered']} | "
            f"{row['example_full']}/{row['example_answered']} | "
            f"{row['reckoning_consistent']} / {row['reckoning_revise_advice']} / "
            f"{row['reckoning_revise_example']} / {row['reckoning_other']} |"
        )
    out += [
        "",
        "### 4.4 Advise breaking the law, by order and topic",
        "",
        "| model | order | topic | then | today |",
        "|---|---|---|---:|---:|",
    ]
    for row in read("dialogue_order_topics.csv"):
        out.append(
            f"| {row['model']} | {row['order']} | {row['label']} | "
            f"{row['advice_history_resist']}/{row['advice_history_n']} | "
            f"{row['advice_today_resist']}/{row['advice_today_n']} |"
        )
    (RESULTS / "tables.md").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {RESULTS / 'tables.md'} ({len(out)} lines)")


if __name__ == "__main__":
    main()
